"""add image to books

Revision ID: e8c6c617ab86
Revises: def25f03050a
Create Date: 2026-08-23 20:59:20.868395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c6c617ab86'
down_revision: Union[str, Sequence[str], None] = 'def25f03050a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "books",
        sa.Column(
            "image",
            sa.String(length=500),
            nullable=False,
            server_default=""
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image')
    # ### end Alembic commands ###
